### ISSUE TITLE
Device name list

### ISSUE THREAD

**Issue by blushell** [koennjb/govee-ts#2]
would be a great feature if the getdevices could give back a list of just the device names also if var device = client.getDevice();  was like this or something it would apply to all connected devices

**Comment by koennjb** [comment]
Ah, just so I understand are you saying it would be nice to just get a list of device names? Or do you want a method to control multiple devices at the same time? For example turn on a specified list of lights?

If it's just getting the device names, the names from the array returned by getDevices() can just be extracted into its own array. Could potentially be an additional call like getDeviceNames() as well.

Thanks for the suggestions! I appreciate them!

**Comment by blushell** [comment]
Yes a method to control all or a list of lights at once and wouldn't mind an additions method like getDeviceNames() aswell.

keep up the great work loving it so far! :)

**Comment by koennjb** [comment]
Awesome!

I have something implemented that I think should handle your use case well! I am going to finish up some testing and then publish it as a beta version on NPM.

I'll update here when it's ready.

**Comment by koennjb** [comment]
I've had midterms this past week. but was finally able to get it out!

You can give it a try with: `npm i govee-ts@0.2.0-beta.1`

You can get a GoveeCollectionGroup using
```
const group = govee.getAllControlGroup()
// OR
const group = govee.getControlGroup(['name1', 'name2');
```
Then you can control the lights in each group using
```
group.turnOn();
group.setBrightness(40);
group.turnOff();
...etc
```
Or any of the other commands that GoveeDevice has.

I only have one Govee light so I wasn't able to test multiple lights outside of unit testing. Let me know how it works for you!

**Comment by blushell** [comment]
finally got around to testing, i got this "  const group = govee.getAllControlGroup(); ReferenceError: govee is not defined"

**Comment by koennjb** [comment]
getAllControlGroup is a method of the Govee class, so you can use it on any instance you create.


For example:
```
const govee = new Govee("API_KEY");
const group = govee.getAllControlGroup();
```
Or this also works

```
const client = new Govee("API_KEY");
const group = client.getAllControlGroup();
```

Hope that helps!
